# Generated by Django 5.0.14 on 2026-03-27 17:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("modelo", models.CharField(max_length=100)),
                ("objeto_id", models.CharField(max_length=100)),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("crear", "Creación"),
                            ("editar", "Edición"),
                            ("eliminar", "Eliminar (Soft Delete)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("detalles", models.JSONField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auditoria_logs",
                "ordering": ["-creado_en"],
            },
        ),
    ]
