# Generated by Django 5.0.14 on 2026-03-27 06:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ayuntamientos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InformeAmbiental",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=200)),
                ("periodo_inicio", models.DateField()),
                ("periodo_fin", models.DateField()),
                ("archivo_pdf", models.FileField(blank=True, upload_to="informes/")),
                (
                    "precio",
                    models.DecimalField(decimal_places=2, default=10000, max_digits=10),
                ),
                ("publicado", models.BooleanField(default=False)),
                ("resumen_ejecutivo", models.TextField(blank=True)),
                ("municipios", models.ManyToManyField(to="ayuntamientos.municipio")),
            ],
            options={
                "db_table": "informes_ambientales",
            },
        ),
        migrations.CreateModel(
            name="EstadisticaDiaria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("fecha", models.DateField()),
                ("total_reportes", models.IntegerField(default=0)),
                ("reportes_resueltos", models.IntegerField(default=0)),
                ("reportes_pendientes", models.IntegerField(default=0)),
                (
                    "tiempo_respuesta_promedio_horas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("nuevos_usuarios", models.IntegerField(default=0)),
                ("usuarios_activos", models.IntegerField(default=0)),
                ("puntos_otorgados", models.IntegerField(default=0)),
                ("zona_mas_activa", models.CharField(blank=True, max_length=150)),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estadisticas",
                        to="ayuntamientos.municipio",
                    ),
                ),
            ],
            options={
                "db_table": "estadisticas_diarias",
                "ordering": ["-fecha"],
                "unique_together": {("municipio", "fecha")},
            },
        ),
    ]
