# Generated by Django 5.0.14 on 2026-03-27 06:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=150)),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("logo", models.ImageField(blank=True, upload_to="municipios/logos/")),
                ("latitud_centro", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "longitud_centro",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "plan_suscripcion",
                    models.CharField(
                        choices=[
                            ("libre", "Libre (Demo)"),
                            ("basico", "Básico — RD$15,000/mes"),
                            ("pro", "Pro — RD$28,000/mes"),
                        ],
                        default="libre",
                        max_length=10,
                    ),
                ),
                ("fecha_inicio_plan", models.DateField(blank=True, null=True)),
                ("fecha_fin_plan", models.DateField(blank=True, null=True)),
                ("contacto_principal", models.EmailField(blank=True, max_length=254)),
                ("telefono_contacto", models.CharField(blank=True, max_length=20)),
                ("esta_activo", models.BooleanField(default=True)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Municipio",
                "verbose_name_plural": "Municipios",
                "db_table": "municipios",
            },
        ),
        migrations.CreateModel(
            name="ZonaCritica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=150)),
                ("latitud", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitud", models.DecimalField(decimal_places=6, max_digits=9)),
                ("radio_metros", models.IntegerField(default=500)),
                ("nivel_prioridad", models.IntegerField(default=1)),
                ("total_reportes", models.IntegerField(default=0)),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zonas",
                        to="ayuntamientos.municipio",
                    ),
                ),
            ],
            options={
                "db_table": "zonas_criticas",
            },
        ),
    ]
