# Generated by Django 5.0.14 on 2026-03-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
