# Generated by Django 5.0.14 on 2026-03-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_usuario_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="cedula",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="usuario",
            name="edad",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
