# Generated by Django 5.0.14 on 2026-03-27 06:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ayuntamientos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaResiduo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=80)),
                ("icono", models.CharField(default="trash", max_length=50)),
                ("color", models.CharField(default="#6B7280", max_length=7)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "categorias_residuos",
            },
        ),
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("latitud", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitud", models.DecimalField(decimal_places=6, max_digits=9)),
                ("direccion", models.CharField(blank=True, max_length=300)),
                ("barrio", models.CharField(blank=True, max_length=100)),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Frente al colmado La Fe",
                        max_length=200,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="reportes/%Y/%m/"
                    ),
                ),
                ("foto_url", models.URLField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de revisión"),
                            ("revisando", "En revisión por el ayuntamiento"),
                            ("en_proceso", "Camión en camino"),
                            ("resuelto", "Resuelto"),
                            ("rechazado", "Rechazado"),
                        ],
                        db_index=True,
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "urgencia",
                    models.IntegerField(
                        choices=[
                            (1, "Baja"),
                            (2, "Media"),
                            (3, "Alta"),
                            (4, "Crítica"),
                        ],
                        default=2,
                    ),
                ),
                ("es_anonimo", models.BooleanField(default=False)),
                ("votos_confirmacion", models.IntegerField(default=0)),
                ("resuelto_en", models.DateTimeField(blank=True, null=True)),
                (
                    "tiempo_respuesta_horas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("nota_resolucion", models.TextField(blank=True)),
                (
                    "foto_resolucion",
                    models.ImageField(
                        blank=True, null=True, upload_to="resoluciones/%Y/%m/"
                    ),
                ),
                ("puntos_otorgados", models.IntegerField(default=0)),
                (
                    "asignado_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reportes_asignados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reportes",
                        to="reportes.categoriaresiduo",
                    ),
                ),
                (
                    "ciudadano",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reportes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes",
                        to="ayuntamientos.municipio",
                    ),
                ),
                (
                    "zona_critica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ayuntamientos.zonacritica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte",
                "verbose_name_plural": "Reportes",
                "db_table": "reportes",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="HistorialEstadoReporte",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("estado_anterior", models.CharField(blank=True, max_length=20)),
                ("estado_nuevo", models.CharField(max_length=20)),
                ("notas", models.TextField(blank=True)),
                (
                    "cambiado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="reportes.reporte",
                    ),
                ),
            ],
            options={
                "db_table": "historial_estados_reporte",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.AddIndex(
            model_name="reporte",
            index=models.Index(
                fields=["estado", "municipio"], name="reportes_estado_36f343_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporte",
            index=models.Index(
                fields=["latitud", "longitud"], name="reportes_latitud_cb4059_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporte",
            index=models.Index(
                fields=["ciudadano", "estado"], name="reportes_ciudada_721777_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporte",
            index=models.Index(
                fields=["creado_en"], name="reportes_creado__89acf5_idx"
            ),
        ),
    ]
