# Generated by Django 5.0.14 on 2026-03-27 06:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comercios", "0001_initial"),
        ("reportes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionPuntos",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("evento", models.CharField(max_length=50, unique=True)),
                ("puntos", models.IntegerField()),
                ("descripcion", models.CharField(max_length=200)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "configuracion_puntos",
            },
        ),
        migrations.CreateModel(
            name="NivelCiudadano",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=50)),
                ("puntos_minimos", models.IntegerField()),
                ("icono", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=7)),
                ("descripcion", models.TextField(blank=True)),
                ("beneficios", models.TextField(blank=True)),
            ],
            options={
                "db_table": "niveles_ciudadano",
                "ordering": ["puntos_minimos"],
            },
        ),
        migrations.CreateModel(
            name="PerfilGamificacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("puntos_totales", models.IntegerField(default=0)),
                ("puntos_canjeados", models.IntegerField(default=0)),
                ("reportes_validos", models.IntegerField(default=0)),
                ("racha_dias", models.IntegerField(default=0)),
                ("ultimo_reporte", models.DateField(blank=True, null=True)),
                ("posicion_ranking", models.IntegerField(blank=True, null=True)),
                (
                    "nivel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gamificacion.nivelciudadano",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_gamificacion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "perfiles_gamificacion",
            },
        ),
        migrations.CreateModel(
            name="TransaccionPuntos",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ganancia", "Ganancia por reporte"),
                            ("canje", "Canje de recompensa"),
                            ("bonus", "Bonus especial"),
                            ("ajuste", "Ajuste administrativo"),
                        ],
                        max_length=15,
                    ),
                ),
                ("puntos", models.IntegerField()),
                ("descripcion", models.CharField(max_length=200)),
                ("saldo_despues", models.IntegerField()),
                (
                    "comercio_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="comercios.comercio",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacciones",
                        to="gamificacion.perfilgamificacion",
                    ),
                ),
                (
                    "reporte_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reportes.reporte",
                    ),
                ),
            ],
            options={
                "db_table": "transacciones_puntos",
                "ordering": ["-creado_en"],
            },
        ),
    ]
