# Generated by Django 5.0.14 on 2026-03-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamificacion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionpuntos",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nivelciudadano",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="perfilgamificacion",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaccionpuntos",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
