# Generated by Django 5.0.14 on 2026-03-27 06:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ayuntamientos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Anuncio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=100)),
                ("descripcion", models.CharField(blank=True, max_length=250)),
                ("imagen", models.ImageField(upload_to="publicidad/")),
                ("url_destino", models.URLField()),
                (
                    "posicion",
                    models.CharField(
                        choices=[
                            ("banner_top", "Banner superior"),
                            ("sidebar", "Barra lateral"),
                            ("card_mapa", "Tarjeta sobre el mapa"),
                            ("panel_ciudadano", "Panel del ciudadano"),
                        ],
                        max_length=30,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("impresiones", models.BigIntegerField(default=0)),
                ("clics", models.BigIntegerField(default=0)),
                (
                    "presupuesto_mensual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "anunciante",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "municipios",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Vacío = todos los municipios",
                        to="ayuntamientos.municipio",
                    ),
                ),
            ],
            options={
                "db_table": "anuncios",
            },
        ),
    ]
