# Generated by Django 5.0.14 on 2026-03-27 06:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ayuntamientos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comercio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre_comercial", models.CharField(max_length=150)),
                ("rif", models.CharField(blank=True, max_length=20)),
                ("descripcion", models.TextField(blank=True)),
                ("logo", models.ImageField(blank=True, upload_to="comercios/logos/")),
                ("direccion", models.CharField(max_length=300)),
                ("barrio", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=20)),
                ("sitio_web", models.URLField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("membresía_activa", models.BooleanField(default=False)),
                ("fecha_inicio_membresia", models.DateField(blank=True, null=True)),
                ("fecha_fin_membresia", models.DateField(blank=True, null=True)),
                (
                    "precio_membresia_mensual",
                    models.DecimalField(decimal_places=2, default=5000, max_digits=10),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ayuntamientos.municipio",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comercio",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "comercios",
            },
        ),
        migrations.CreateModel(
            name="Recompensa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=150)),
                ("descripcion", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("descuento_porcentaje", "Descuento porcentual"),
                            ("producto_gratis", "Producto gratis"),
                            ("servicio", "Servicio"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "valor_descuento",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="% si es descuento",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("puntos_requeridos", models.IntegerField()),
                ("stock", models.IntegerField(default=-1)),
                ("canjes_totales", models.IntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                ("imagen", models.ImageField(blank=True, upload_to="recompensas/")),
                (
                    "comercio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recompensas",
                        to="comercios.comercio",
                    ),
                ),
            ],
            options={
                "db_table": "recompensas",
            },
        ),
        migrations.CreateModel(
            name="CanjeRecompensa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("codigo_canje", models.CharField(max_length=20, unique=True)),
                ("usado", models.BooleanField(default=False)),
                ("usado_en", models.DateTimeField(blank=True, null=True)),
                ("puntos_usados", models.IntegerField()),
                (
                    "ciudadano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canjes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recompensa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canjes",
                        to="comercios.recompensa",
                    ),
                ),
            ],
            options={
                "db_table": "canjes_recompensas",
            },
        ),
    ]
